### ISSUE TITLE
Ranking Game: Error about generating `costs`

### ISSUE THREAD

**Issue by shizejin** [oyamad/QuantEcon.py#2]
https://github.com/oyamad/QuantEcon.py/blob/ffc57d1fe6f56205e1d125ac0672260f092ab079/quantecon/game_theory/game_generators/bimatrix_generators.py#L214-L216

Error messages generated by the lines above:

```Python
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

This is because `costs` is ndarray with dtype being `int`, and the casting with the rule `same_kind` has been deprecated. (see discussion [here](https://github.com/numpy/numpy/issues/6464)).

My proposal is:

```Python
costs = np.empty((2, n-1))
costs[:] = random_state.randint(1, steps+1, size=(2, n-1))
np.cumsum(costs, axis=1, out=costs)
costs[:] /= (n * steps)
```

**Comment by oyamad** [comment]
Thanks, good point. Done in 36ac2cb63c8df40e5ae7c8c8105870c21c292a0a.
